### ISSUE TITLE
crates publishing team

### ISSUE THREAD

**Issue by michaelkirk** [georust/gdal#110]
👋 Hi @jdroenner and @frewsxcv,  

Following up on https://github.com/georust/meta/pull/21, I created a new org team with you two as maintainers. Could you please [update the crate owners](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner)? I'm assuming it makes sense to share a single team for these two crates, but feel free to do otherwise.

Specifically:

---

- [ ] @frewsxcv: update **gdal crate** owners on crates.io:

```
cd gdal

# 💥 remove large publishing group
cargo owner --remove github:georust:core
# 🔐 add small publishing group
cargo owner --add github:georust:gdal-publishers

# 🚨 consider adding jdroenner as a user-owner, as they have been maintaing and publishing recently
cargo owner --add jdroenner

# 🚨 consider removing mgax as a user-owner, since they expressed no longer being actively involved in the project
cargo owner --remove mgax

# 🚨 and from https://github.com/orgs/georust/teams/gdal-publishers

# make sure everything looks good 👀 
cargo owner --list
```
---

- [ ] @jdroenner: update **gdal-sys crate** owners on crates.io:

@jdroenner - you're the only "user owner" of that crate, so only you can edit that crate's owners:

```
cd gdal-sys

# 💥 remove large publishing group
cargo owner --remove github:georust:core
# 🔐 add small publishing group
cargo owner --add github:georust:gdal-publishers

# and consider another user-owner, that way if for some reason you become inaccessible
# we have someone else who can edit the owners. See https://github.com/rust-lang/crates.io/issues/2906
cargo owner --add <username>

# make sure everything looks good 👀 
cargo owner --list
```
---

And if there's anyone else you'd like to be able to publish the crates, feel free to add them to your publishing team, or as a user-owner. Consider that user-owners, as opposed to owners-via-team, can themselves edit the crate's owners, which could be desirable, or not, depending.

Let me know if you have any questions, or you can review https://github.com/georust/meta/pull/21.

**Comment by mgax** [comment]
Hey @michaelkirk, thanks for organizing the crate owners discussion! I haven't been involved in rust-gdal for quite a while so feel free to remove me from the list of crate owners; it looks like @jdroenner is taking good care of the project :)

**Comment by michaelkirk** [comment]
Thanks for the response @mgax! 

I can't actually edit the crate owners, but I see that @frewsxcv is also a user-owner of the gdal crate, so I've updated the instructions for him, and then expect @jdroenner should be able to update the gdal-sys crate.

**Comment by jdroenner** [comment]
i changed the gdal-sys team. Who wants to be a gdal-sys owner? :grinning:

**Comment by frewsxcv** [comment]
@jdroenner feel free to add me on gdal-sys if you want! otherwise this issue is done. i just took care of the gdal crate
