### ISSUE TITLE
0.7 docs.rs build failed

### ISSUE THREAD

**Issue by dead10ck** [georust/gdal#130]
The docs.rs build for 0.7 failed: https://docs.rs/crate/gdal/0.7.0

**Comment by michaelkirk** [comment]
Hopefully this will be fixed by https://github.com/georust/gdal/pull/128 once the next release is published.

**Comment by dead10ck** [comment]
Sorry, I'm not really familiar with how docs.rs works, but is there a way to fix the build without waiting for a new release? It looks like there are significant changes in 0.7 and having up to date docs would help. Also the docs published in the link in the README appear to be even older.

**Comment by michaelkirk** [comment]
docs.rs is based on the published crates, so it won't be updated until the next crate version is released.

In the meanwhile, you can build the docs locally:

```
git clone https://github.com/georust/gdal
cd gdal
cargo doc
# on macos, or just point your browser at this file
open target/doc/gdal/index.html
```

**Comment by michaelkirk** [comment]
> Also the docs published in the link in the README appear to be even older.

Thanks for pointing this out! I've proposed a fix here: https://github.com/georust/gdal/pull/131

**Comment by jdroenner** [comment]
Thanks. I will release 0.7.1 to fix this soon.

**Comment by jdroenner** [comment]
so it turns out the fix is file for gdal-sys but the build script of gdal still fails. i guess we will need something more complex from here: https://github.com/rust-lang/docs.rs/issues/147

**Comment by jdroenner** [comment]
the docs.rs build is now working :tada:
