### ISSUE TITLE
Any way of selecting GDALRIOResampleAlg?

### ISSUE THREAD

**Issue by spadarian** [georust/gdal#140]
At the moment, to read a raster into a slice you are using [GDALRasterIO](https://github.com/georust/gdal/blob/1ee19ed1ea3da385dfc1dd47090e5a42b7b3bffc/src/raster/rasterband.rs#L89), which doesn't provide a way to select a resampling algorithm.

If I'm not mistaken, [GDALRasterIOEx](https://github.com/georust/gdal/blob/2fadecc39c84c317ca023cfaf67fd6fbd0c568a5/gdal-sys/prebuilt-bindings/gdal_2.4.rs#L6156) has an extra option which could be used to do that.

Is there any way to pass a sampling algorithm ([GDALRIOResampleAlg](https://github.com/georust/gdal/blob/2fadecc39c84c317ca023cfaf67fd6fbd0c568a5/gdal-sys/prebuilt-bindings/gdal_2.4.rs#L5285)) to `read_as` or `read_into_slice`?

I tried to implement my own `read_into_slice` function but `RasterBand.c_rasterband` is private and I'm not sure how to proceed.

Cheers!

**Comment by jdroenner** [comment]
I guess we should change the `read_as` and `read_into_slice` methods to use GDALRasterIOEx. It would be great if you could provide a PR for this. You could have a look at GdalOpenEx in dataset.rs for an example.
