### ISSUE TITLE
RFC: handle getters (`c_dataset` and friends) should be safe

### ISSUE THREAD

**Issue by lnicola** [georust/gdal#168]
The Rust convention is to place `unsafe` at the usage site, e.g. `as_ptr` is safe, but dereferencing the pointer is not. We should follow the same convention.

**Comment by rmanoka** [comment]
I would be a bit more confident with changing the `pub(crate)` ones to begin with.

**Comment by metasim** [comment]
Closed by https://github.com/georust/gdal/pull/447
