### ISSUE TITLE
RFC: drop datetime feature (or drop `FieldValue`)

### ISSUE THREAD

**Issue by lnicola** [georust/gdal#169]
I think we should drop the feature and eat the extra dependency.

`chrono` builds in about 3 seconds and having different code paths can be annoying (see https://github.com/georust/gdal/pull/164/commits/37657367902b3e53359b48aed97c220bfddb12b2 for a recent example, where `clippy` failed because of an apparently infallible function returning `Result`).

**Comment by lnicola** [comment]
One more argument for this: feature-gating an enum value can make dependent crates stop building if the feature gets pulled in by another crate. I gave an example in https://github.com/georust/wkt/issues/50#issuecomment-789078596.

**Comment by lnicola** [comment]
On the other hand, we could try to do this "the right way" and define a set of conversion traits. This way we could get rid of the enum and still be able to make the `chrono` dependency optional.

**Comment by ChristianBeilschmidt** [comment]
For me, time is essential to geoprocessing, so I don't see the point in having this feature-gated.

And if we keep it, I guess you are right in working on the enum value.

**Comment by jdroenner** [comment]
if i get it right the issue is with localtime and time removed that in 0.3. I guess we will never need local time and should be able to use time instead.
