### ISSUE TITLE
Missing support for layer creation options

### ISSUE THREAD

**Issue by ttencate** [georust/gdal#185]
I need to pass `OVERWRITE=YES` in case the target layer already exists, so passing `null_mut()` as the last argument to `OGR_DS_CreateLayer` is counterproductive for me.

I propose to merge `create_layer` and `create_layer_blank` into a single function, `create_layer`, which takes a new `struct LayerOptions` that implements `Default`. This is consistent with how `Dataset::open_ex` works with `DatasetOptions`.

I'll create a PR soon, but if anyone already has some input, please give a shout.

**Comment by jdroenner** [comment]
sounds like a good idea
