### ISSUE TITLE
Can ResampleAlg be exported?

### ISSUE THREAD

**Issue by ktmattson-alion** [georust/gdal#188]
`RasterBand::read_as(..)` and the rest take `Option<ResampleAlg>`. But that enum is public-but-not-exported, so the only choice to the user is `None`.

Is this by design? I noticed that the tests use `crate::raster::rasterband::ResampleAlg;` so perhaps the re-export from `mod raster` was overlooked.

Thanks for your time.

**Comment by lnicola** [comment]
I can't check right now, but it sounds like an oversight. Do you want to submit a PR?

**Comment by ktmattson-alion** [comment]
I can -- but off the clock ;)
