### ISSUE TITLE
repo cleanup - remove unused 'github-pages' environment

### ISSUE THREAD

**Issue by michaelkirk** [georust/gdal#207]
Visible from the repo front page:
<img width="369" alt="Screen Shot 2021-08-04 at 1 13 10 PM" src="https://user-images.githubusercontent.com/217057/128248420-5537bca6-6738-4433-893c-80c6efdbfebd.png">

It seems like a vestige leftover from when we generated our own docs, rather than using docs.rs, and the url currently 404s.

I'm pretty sure we can just delete it, but wanted to double check in case someone had some weird use case for it.

<img width="1072" alt="Screen Shot 2021-08-04 at 1 14 02 PM" src="https://user-images.githubusercontent.com/217057/128248528-b46f16d3-24cd-4f84-bd0c-a5669477deac.png">

**Comment by jdroenner** [comment]
yes we should remove it

**Comment by michaelkirk** [comment]
done!
