### ISSUE TITLE
Read-only Dataset?

### ISSUE THREAD

**Issue by spadarian** [georust/gdal#210]
Do you think it could be possible to implement a read-only version of `Dataset`?

I'm asking because `Dataset` is `!Sync` due to a mutable pointer... but maybe it is possible to read from that pointer concurrently?

Actuallym I have no idea if it's possible... :smile:

**Comment by lnicola** [comment]
It's not, you need to open it twice:

> the same `​GDALDataset` object should not be accessed by several threads at the same time

([source](https://trac.osgeo.org/gdal/wiki/FAQMiscellaneous#IstheGDALlibrarythread-safe))

The reason for that is that most libraries aren't thread-safe -- they have a single context for the whole dataset and/or they use the file cursor position when reading.

**Comment by spadarian** [comment]
I see... Thanks @lnicola
