### ISSUE TITLE
docs.rs should include `array` feature

### ISSUE THREAD

**Issue by msalib** [georust/gdal#228]
It would be nice if we enabled at least the `array` feature for docs.rs by adding this to `Cargo.toml`:
```
[package.metadata.docs.rs]
features = ["array"]
```
Perhaps adding `datetime` to that list would be good as well.

The goal here is that someone looking at docs.rs should know that the array methods actually exist because otherwise, they're very easy to miss.

**Comment by ChristianBeilschmidt** [comment]
I really like the idea and I also think we should add these `cfg_attr`s at the same time.

Maybe we can save some time in the realization if we decide on this first: https://github.com/georust/gdal/issues/169
But nevertheless, it should be a manageable effort.
