### ISSUE TITLE
Multidimensional Raster Data Model not yet supported.

### ISSUE THREAD

**Issue by geohardtke** [georust/gdal#232]
GDAL introduced the `Multidimensional Raster Data Model` upstream in version 3.1, and we don't have support for it in this crate. 

I explored the API recently and wrote a few wrappers (See linked [PR](https://github.com/georust/gdal/pull/233) ). It is still very rough, but it could be a useful starting point for a  discussion in case there is some interest in supporting this.

So, please review the code and let me know what you think.

**Comment by ChristianBeilschmidt** [comment]
@jdroenner merged #273 so we can close this here as we have initial support.
