### ISSUE TITLE
GPKG layer with dash causes an error

### ISSUE THREAD

**Issue by DmitriLebedevArammeem** [georust/gdal#235]
This code works but prints an SQLite error that it can't delete trigger rtreee_<layer_name> because of syntax error at "-" -- the name of the trigger is unquoted, and dash is a minus sign.

In GDAL this error has been [fixed](https://trac.osgeo.org/gdal/ticket/5472) years ago, and my version is much newer (3.2) than then (2.0). What's going on and is it possible to fix this?

	use std::path::Path;
	use gdal::{Dataset, DatasetOptions, GdalOpenFlags};
	use gdal::vector::FieldValue;

	fn main() {
		let dso = DatasetOptions { open_flags: GdalOpenFlags::GDAL_OF_READONLY | GdalOpenFlags::GDAL_OF_UPDATE, allowed_drivers: Some(&["GPKG", "GeoJSON"]), open_options: None, sibling_files: None };
		let dataset = Dataset::open_ex(Path::new("flat-sale.gpkg"), dso).expect("failed to open gpkg file");

		let mut layer = dataset.layer(0).unwrap();
		let mut area:f64 = 0.0;
		let mut rows:i32 = 0;
		for feature in layer.features() {
			let highway_field = feature.field("total_area").unwrap().unwrap();
			rows += 1;
			match highway_field {
				FieldValue::IntegerValue(i) => { area += i as f64; },
				FieldValue::Integer64Value(i) => { area += i as f64; },
				FieldValue::RealValue(i) => { area += i; },
				_ => {}
			}
		}
		println!("AREA {:?} ROWS {} MEAN AREA {}", area, rows, area / rows as f64);
	}

Output:

    ERROR 1: sqlite3_exec(DROP TRIGGER rtree_flat-sale_geom_update3) failed: near "-": syntax error
    ERROR 1: sqlite3_exec(CREATE TRIGGER "rtree_flat-sale_geom_update3" AFTER UPDATE ON "flat-sale"
    WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN 
    DELETE FROM "rtree_flat-sale_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_flat-sale_geom" 
    VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom"));
    END) failed: trigger "rtree_flat-sale_geom_update3" already exists

    AREA 59143095.80000853 ROWS 996284 MEAN AREA 59.36369127679309
    1 seconds

**Comment by lnicola** [comment]
I tried, but I couldn't reproduce it with a simplified version of the code:

```rust
use gdal::vector::FieldValue;
use gdal::{Dataset, DatasetOptions, GdalOpenFlags};
use std::path::Path;

fn main() {
    let dso = DatasetOptions {
        open_flags: GdalOpenFlags::GDAL_OF_READONLY | GdalOpenFlags::GDAL_OF_UPDATE,
        allowed_drivers: Some(&["GPKG", "GeoJSON"]),
        open_options: None,
        sibling_files: None,
    };
    let dataset = Dataset::open_ex(Path::new("a-b.gpkg"), dso).expect("failed to open gpkg file");

    let mut layer = dataset.layer(0).unwrap();
    let mut rows: i32 = 0;
    for feature in layer.features() {
        rows += 1;
    }
    println!("ROWS {}", rows);
}
```

In any case, it sounds like a GDAL and/or SQLite issue. Can you test in a Docker container like `osgeo/gdal:ubuntu-full-3.2.0`?

**Comment by rouault** [comment]
GDAL upstream issue just fixed per https://github.com/OSGeo/gdal/commit/9452625baa544ea3ab6bb0b3e368023434011ea7

**Comment by lnicola** [comment]
Fixed upstream, thanks Even. My reproduction didn't work because my table name probably didn't actually contain a dash.

**Comment by rouault** [comment]
> My reproduction didn't work because my table name probably didn't actually contain a dash.

more subtle than that: the table name must contain a dash and have been created with the buggy triggers as defined in the GeoPackage < 1.2.1 spec (so with a quite ancient GDAL version)
