### ISSUE TITLE
Setup to use on windows

### ISSUE THREAD

**Issue by jackyarndley** [georust/gdal#243]
Hi, thanks for the library and bindings. 

I've been trying to get this to work on windows. Problems arise whilst linking to the GDAL libraries:

- I've tried using [GIS Internals](https://gisinternals.com/release.php) to download windows builds, and then set the `GDAL_HOME` (etc) environment variables to the values in this. After fixing a few errors, I am left with an error saying ENTRY_POINT_NOT_FOUND, which I think is for the dll/lib entry point. This was present both using bindgen and without.
- Also tried using MSYS2 MINGW but with no more success.
- Tried both the MSVC and GNU toolchains.

Would it be possible to get some more details on how to setup a working environment (a bit more than #179), so that this can be used on windows?

Thanks.

**Comment by pka** [comment]
The Windows CI build https://github.com/georust/gdal/pull/218/files should work with current master branch.

**Comment by jackyarndley** [comment]
Thanks. I had tried that previously but did so again and eventually discovered that an old QGIS installation took precedence, and provided different gdal libraries. Once this was removed it worked straight away.

Thanks for your help.
