### ISSUE TITLE
How do you write an `Array2` to a `Dataset`/`RasterBand`?

### ISSUE THREAD

**Issue by metasim** [georust/gdal#253]
I'm using `read_as_array` to get the `ndarray` form of the raster data, due to its convenience. After manipulation, how do I write that data into a new RasterBand, minimizing copies?

**Comment by jdroenner** [comment]
To be honest i never tried that. I guess you need to get the slice from an OwnedArray and use that.

**Comment by rmanoka** [comment]
Somethine like this should work:

```
use gdal::raster::Buffer;
let (ysize, xsize) = data.dim();
band.write(
    (0, y),
    (xsize, ysize),
    &Buffer::new((xsize, ysize), data.into_raw_vec()),
)?;
```

It writes the block of dim `(xsize X ysize)` to a window `(0, y)  <-> (xsize X y + ysize)`.  
It does involve moving from nd-array -> vec.  So if you need to keep the array, you'll have to convert back to the nd-array.  It involves moving about one pointer word but doesn't move the data.

**Comment by metasim** [comment]
Fantastic! Thanks for the help!
