### ISSUE TITLE
Misleading panic in gdal-sys build script

### ISSUE THREAD

**Issue by ttencate** [georust/gdal#255]
This looks dodgy:

https://github.com/georust/gdal/blob/0747fa6d05f993a878e792ba98770027fb99cf1d/gdal-sys/build.rs#L131-L136

I suppose the panic text should say windows-msvc instead of windows-gnu, but for all I know it might be the other way around, which would mean the condition and subsequent comment are wrong.

**Comment by lnicola** [comment]
Fixed in #332.
