### ISSUE TITLE
Dynamic handling of cell types

### ISSUE THREAD

**Issue by metasim** [georust/gdal#256]
I'm wondering if there are examples or tips to share on implementing operations where the cell type for read and write operations is dynamically determined at runtime.  For example, let's say I have a program that adds two rasters together and writes the result. If the input rasters are `u8`, I'd like the output to be `u8`, if `u16`, then `u16`, etc. 

Because the cell type is a type parameter to `read_as` and `write` (via `Buffer<T: GdalType>`), I'm thinking this isn't supported, and my best bet is to bypass the Rust wrappers and use the C functions that accept cell type as `GDALDataType` (which is actually `libc::c_uint`).  I'd obviously rather not do that, so thought I'd check here first. I'm fairly new to Rust, so I recognize I may be looking at the problem in the wrong way.

**Comment by lnicola** [comment]
You should be able to check the data type, `match` on it, then use `read_as` with the expected type parameter on each of the `match` arms. It's a bit ugly, but even if you use the `C` API you have to pick between converting to a wider type and typing a bit of code.

**Comment by metasim** [comment]
> even if you use the C API you have to pick between converting to a wider type and typing a bit of code

I assume this is because the returned `Buffer<T>` has an underlying size, and being generic on read/write only pushes the ball a little down the field?

I started going down this path, not realizing `GdalType` doesn't reference `self` until the end. 😆 

```rust
struct DynamicGDALDataType(gdal_sys::GDALDataType::Type);
impl From<gdal_sys::GDALDataType::Type> for DynamicGDALDataType {
    fn from(ct: gdal_sys::GDALDataType::Type) -> Self {
        Self(ct)
    }
}
impl GdalType for DynamicGDALDataType {
    fn gdal_type() -> GDALDataType::Type {
        // ooops... no self :/
        unimplemented!()
    }
}
```

I think I'll dig into some of the C-based gdal tools and see how they approach this problem. Thanks for the response!

**Comment by jdroenner** [comment]
yes, You should check the type and then match on it. You can write your implementation with generics and then call it in the match block with the right type. However, you need to keep the buffer in an enum or do the processing in a typed function.

We do something similar in Geo Engine. We already know that type we expect to load.  Then we load the right type and push it through the Engine. https://github.com/geo-engine/geoengine/blob/master/operators/src/source/gdal_source/mod.rs#L590 The code is a bit complex but i think you get the idea.

**Comment by metasim** [comment]
Awesome help! Thanks so much! 🥇 

Have you considered enabling Discussions on this repo? I'm sure I'm not the first to ask some of these questions...
