### ISSUE TITLE
Consider enabling CI for PRs

### ISSUE THREAD

**Issue by lnicola** [georust/gdal#266]
I think we should enable CI for incoming pull requests. From previous discussions, the main concern was the possibility that a PR was doing something malicious. I think that's not much of an issue because pull requests don't have access to any of the secrets stored in the main repository:

> Secrets are not passed to workflows that are triggered by a pull request from a fork.

This is safer than giving commit rights to more people and asking them to push their branch to the main repo.

**Comment by michaelkirk** [comment]
This seems to be done - closing.
