### ISSUE TITLE
Plans to publish 0.13.0?

### ISSUE THREAD

**Issue by metasim** [georust/gdal#288]
Would love to see the latest batch of PRs released to crates.io. What help might be needed to make that happen?

---

Dependencies:

- [x] https://github.com/georust/gdal/pull/279
- [x] https://github.com/georust/gdal/pull/281
- [x] https://github.com/georust/gdal/pull/284
- [x] https://github.com/georust/gdal/pull/285
- [x] https://github.com/georust/gdal/pull/289
- [x] https://github.com/georust/gdal/pull/291

**Comment by jdroenner** [comment]
i guess we should merge

#279
#281 
#284 

and

#285 

then i can create a new release. I guess it is possible to do that this week.

**Comment by ChristianBeilschmidt** [comment]
Can https://github.com/georust/gdal/pull/289 and https://github.com/georust/gdal/pull/291 maybe be part of it as well?

**Comment by metasim** [comment]
@jdroenner Do we want to hold back the release for #289 and #291 to get merged, or do we prefer a "release now and soon after" approach?

**Comment by lnicola** [comment]
I think it would make sense to merge them (I'll take another look at them in the next few days), but also fix #290.

**Comment by jdroenner** [comment]
all the PRs i wanted to see in the release are merged now. I will prepare a new release now :)

**Comment by lnicola** [comment]
What about #290?

**Comment by lnicola** [comment]
I might have a quick fix for it, if you want to wait.

**Comment by jdroenner** [comment]
yes i can wait

**Comment by metasim** [comment]
@here Thanks to everyone for making this release happen! I very much appreciate it, as I assume others will! 🥇
