### ISSUE TITLE
Crash in `...::test_features_aliasing_compile_fail` on MacOS M1

### ISSUE THREAD

**Issue by metasim** [georust/gdal#312]
This is on `master` (0.13.0).

This crash doesn't appear to happen in CI, but locally I can't run tests without it happening.

Run with `cargo test vector -- test_features_aliasing_compile_fail`

## Versions

    ❯ rustc -V
    rustc 1.62.1 (e092d0b6b 2022-07-16)

    ❯ cargo -V
    cargo 1.62.1 (a748cf5a3 2022-06-08)

    ❯ gdalinfo --version
    GDAL 3.5.1, released 2022/06/30

```console
❯ otool -L .../gdal-1d948e2c1e5d4df0
.../gdal-1d948e2c1e5d4df0:
	/opt/homebrew/opt/gdal/lib/libgdal.31.dylib (compatibility version 32.0.0, current version 32.1.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```	    

## Backtrace

    ❯ uname -a
    Darwin MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

```console
test vector::vector_tests::tests::test_features_aliasing_compile_fail ... FAILED

failures:

---- vector::vector_tests::tests::test_features_aliasing_compile_fail stdout ----
thread 'vector::vector_tests::tests::test_features_aliasing_compile_fail' panicked at '1 of 1 tests failed', /Users/sfitch/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.55/src/run.rs:74:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: trybuild::run::<impl trybuild::Runner>::run
             at /Users/sfitch/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.55/src/run.rs:74:13
   3: <trybuild::TestCases as core::ops::drop::Drop>::drop
             at /Users/sfitch/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.55/src/lib.rs:308:13
   4: core::ptr::drop_in_place<trybuild::TestCases>
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ptr/mod.rs:486:1
   5: gdal::vector::vector_tests::tests::test_features_aliasing_compile_fail
             at ./src/vector/vector_tests/mod.rs:808:5
   6: gdal::vector::vector_tests::tests::test_features_aliasing_compile_fail::{{closure}}
             at ./src/vector/vector_tests/mod.rs:805:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    vector::vector_tests::tests::test_features_aliasing_compile_fail
```

**Comment by lnicola** [comment]
Can you compile the code it's testing? Easiest is probably to turn it into an example.

This isn't the first time trybuild is causing us problems, and I've also seen it fail when testing locally one of your PRs (I forgot why).

**Comment by metasim** [comment]
> Can you compile the code it's testing? 

I'm not familiar enough with what's going on here to know what you mean... I'm guessing you mean something other than `cargo test`?

**Comment by lnicola** [comment]
Yeah, copy the file in https://github.com/georust/gdal/tree/master/tests/compile-tests to `examples`, then try to build it with `cargo check --example 01-features-aliasing-errors.rs`. It's supposed to fail with the error in https://github.com/georust/gdal/blob/master/tests/compile-tests/01-features-aliasing-errors.stderr, but if the compiler output ever changes, the test starts failing.

**Comment by metasim** [comment]
@lnicola :

Transcript:

```
❯ git rev-parse --short HEAD
24280ad
❯ cp tests/compile-tests/*.rs examples
❯ cargo check --example 01-features-aliasing-errors
...
error[E0502]: cannot borrow `layer` as immutable because it is also borrowed as mutable
  --> examples/01-features-aliasing-errors.rs:10:17
   |
9  |     for _ in layer.features() {
   |              ----------------
   |              |
   |              mutable borrow occurs here
   |              mutable borrow later used here
10 |         let _ = layer.defn();
   |                 ^^^^^^^^^^^^ immutable borrow occurs here

For more information about this error, try `rustc --explain E0502`.
error: could not compile `gdal` due to previous error


```

```
❯ cat tests/compile-tests/01-features-aliasing-errors.stderr
error[E0502]: cannot borrow `layer` as immutable because it is also borrowed as mutable
  --> $DIR/01-features-aliasing-errors.rs:10:17
   |
9  |     for _ in layer.features() {
   |              ----------------
   |              |
   |              mutable borrow occurs here
   |              mutable borrow later used here
10 |         let _ = layer.defn();
   |                 ^^^^^^^^^^^^ immutable borrow occurs here
```

Seems to be the same.. 🤔 I'll dig further.

**Comment by lnicola** [comment]
Ah, I missed this. Are your saying that `cargo test vector -- test_features_aliasing_compile_fail` actually fails reliably?

**Comment by lnicola** [comment]
Could it be a whitespace difference like tabs vs. spaces, or related to the EOLs? You could try updating to a newer version.

**Comment by metasim** [comment]
> Are your saying that cargo test vector -- test_features_aliasing_compile_fail actually fails reliably?

Yep... Test never passes on my local machine. I'll do a manual diff next.

<details>
<pre>

test tests/compile-tests/01-features-aliasing-errors.rs ... mismatch

EXPECTED:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0502]: cannot borrow `layer` as immutable because it is also borrowed as mutable
  --> $DIR/01-features-aliasing-errors.rs:10:17
   |
9  |     for _ in layer.features() {
   |              ----------------
   |              |
   |              mutable borrow occurs here
   |              mutable borrow later used here
10 |         let _ = layer.defn();
   |                 ^^^^^^^^^^^^ immutable borrow occurs here
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

ACTUAL OUTPUT:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
note: If the actual output is the correct output you can bless it by rerunning
      your test with the environment variable TRYBUILD=overwrite



test vector::vector_tests::tests::test_features_aliasing_compile_fail ... FAILED

failures:

---- vector::vector_tests::tests::test_features_aliasing_compile_fail stdout ----
thread 'vector::vector_tests::tests::test_features_aliasing_compile_fail' panicked at '1 of 1 tests failed', /Users/sfitch/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.55/src/run.rs:74:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    vector::vector_tests::tests::test_features_aliasing_compile_fail

test result: FAILED. 82 passed; 1 failed; 0 ignored; 0 measured; 118 filtered out; finished in 0.14s

</pre>
</details>

**Comment by metasim** [comment]
This is mostly just annoying. To get around it I just run with `TRYBUILD=overwrite` and move on. Not sure I understand what is being achieved with this test anyway.

**Comment by lnicola** [comment]
Yeah, I had problems un more exotic cases, like running the tests under gdb. Can you update trybuild, if it's not already picking up the latest version?

I'm (still) if favour of removing the whole thing.

**Comment by lnicola** [comment]
This is very far-fetched, but can you try one more thing? You're using IntelliJ, right? Try to close your IDE, run cargo clean, and then cargo test.

**Comment by metasim** [comment]
> This is very far-fetched

Hah! I was almost convince you were right off the bat!... however... 😞 

<details>
<pre>
❯ cargo clean && cargo test
...
test tests/compile-tests/01-features-aliasing-errors.rs ... error
Expected test case to fail to compile, but it succeeded.



test vector::vector_tests::tests::test_features_aliasing_compile_fail ... FAILED

failures:

---- vector::vector_tests::tests::test_features_aliasing_compile_fail stdout ----
thread 'vector::vector_tests::tests::test_features_aliasing_compile_fail' panicked at '1 of 1 tests failed', /Users/sfitch/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.71/src/run.rs:101:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    vector::vector_tests::tests::test_features_aliasing_compile_fail

test result: FAILED. 200 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.38s

error: test failed, to rerun pass '--lib'
</pre>
</details>

Good guess tho!
