### ISSUE TITLE
Release `0.13.1` or `0.14.0`?

### ISSUE THREAD

**Issue by metasim** [georust/gdal#315]
Primarily, I think it would be nice to replace the sparse public entry points below...

<table>
<tr><td>
<img width="400" alt="image" src="https://user-images.githubusercontent.com/131013/194194880-6a636245-69e4-45ce-8ba2-ba9c56898f33.png"></td><td>
<img width="400" alt="image" src="https://user-images.githubusercontent.com/131013/194195048-63a2c477-2c64-4b92-8735-658f7bc15bdc.png"></td></tr>
</table>

...with the updated docs that came after the `0.13.0` release, as a `0.13.1`:

<img width="989" alt="image" src="https://user-images.githubusercontent.com/131013/194195427-b22b7dae-a140-4f55-ac72-c99acc1c83ab.png">

However, there are enough new features as well that perhaps this warrants `0.14.0`?

---

- Added new content to `README.md` and the root docs.

  - <https://github.com/georust/gdal/pull/296>

- Fixed a crash in `Group::dimensions` and `MDArray::dimensions` when no dimensions exist

  - <https://github.com/georust/gdal/pull/303>

- Added a more ergonomic means of accessing GDAL version properties

  - <https://github.com/georust/gdal/pull/305>

- Provided access to `gdal-sys` discriminant values in `ResampleAlg` enum.

  - <https://github.com/georust/gdal/pull/309>

- **Breaking** `RasterBand::set_no_data_value` takes `Option<f64>` instead of `f64` so that no _no-data_ can be set.
  Also makes it symmetric with `RasterBand::no_data_value` which returns `Option<f64>`.

  - <https://github.com/georust/gdal/pull/308>

- Added quality-of-life features to `CslStringList`: `len`, `is_empty`, `Debug` and `Iterator` implementations. 

  - <https://github.com/georust/gdal/pull/311>

- Added ability to set color table for bands with palette color interpretation. 
  Added ability to create a color ramp (interpolated) color table.

  - <https://github.com/georust/gdal/pull/314>
  -

**Comment by metasim** [comment]
@jdroenner polite bump? 😃

**Comment by jdroenner** [comment]
sooooo how about a new release this week? :see_no_evil: 
Are there open PRs we want to merge first?

**Comment by lnicola** [comment]
https://github.com/georust/gdal/pull/318/files maybe?

**Comment by metasim** [comment]
> #318 maybe?

That would be nice, but I wouldn't hold back the release if major changes are required.
