### ISSUE TITLE
`gdal::raster::rasterband::RasterBand::band_type` still returns a `GDALDataType::Type`

### ISSUE THREAD

**Issue by ChristianBeilschmidt** [georust/gdal#333]
There seemed to be a change of replacing the `GDALDataType` with a crate enum `GdalDataType`.
However, the `RasterBand` still returns the `u32`: https://github.com/georust/gdal/blob/3eefd647a9d9fdd6d8a11d914f68657800c6fc9f/src/raster/rasterband.rs#L479

Was is intended or forgotten?

**Comment by metasim** [comment]
@ChristianBeilschmidt Forgotten 😞 Thanks for catching this. :)
