### ISSUE TITLE
Build script version detection assumes you're not cross compiling

### ISSUE THREAD

**Issue by sfackler** [georust/gdal#376]
The gdal crate declares gdal-sys as both a runtime and build-time dependency, and calls the gdal_version_docs_rs_wrapper function to determine the gdal version.

This logic is broken when cross compiling, since the host system's gdal won't be the same as the target system's gdal. A more robust approach would be to have gdal-sys output the detected version in its build script which can then be picked up by gdal's build script: 

https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key
https://doc.rust-lang.org/cargo/reference/build-script-examples.html#using-another-sys-crate

**Comment by rmanoka** [comment]
Indeed, this was done to get it working on docs.rs which does a cross-compilation, and we wanted to be able to not rely on the host (docs.rs) having gdal installed.  Ref. [PR that introduced it](https://github.com/georust/gdal/pull/281) for discussion.  I believe the standard `DOCS_RS` flag approach was causing issues for the docs.rs builds of down-stream libraries.

Do you have a MWIP repo to test?  I'm not an expert on cross comp.

**Comment by sfackler** [comment]
The issue isn't related to the docs.rs stuff, just to the fact that [this dependency](https://github.com/georust/gdal/blob/master/Cargo.toml#L29-L30) exists at all.

**Comment by jdroenner** [comment]
Well, if there is a better way, let us use that. I

**Comment by lnicola** [comment]
@sfackler how can `gdal` know the version that `gdal-sys` detected without depending on it?

**Comment by sfackler** [comment]
It currently depends on it twice. This is the dependency that should stay: https://github.com/georust/gdal/blob/master/Cargo.toml#L23

**Comment by lnicola** [comment]
So if I got this right:

 - `gdal-sys` needs a `links = "gdal"` clause and can output a `cargo:version_number` declaration
 - `cargo` makes sure that the `gdal` build script gets a `DEP_GDAL_VERSION_NUMBER` env variable with the value set by `gdal-sys`

That's quite nifty, I didn't know it was a thing.

**Comment by sfackler** [comment]
Yep!

**Comment by rmanoka** [comment]
So this means we can also test the docs_rs variable somewhere and output the appropriate env. variables?

**Comment by jdroenner** [comment]
i guess it should work like this: #377

**Comment by lnicola** [comment]
Fixed in #377 :tada:

**Comment by sfackler** [comment]
Thanks for the quick fix!
