### ISSUE TITLE
Error building on mac

### ISSUE THREAD

**Issue by milosimr** [georust/gdal#387]
Since a couple of days ago, homebrew updated gdal and this package no longer compiles:

```
thread 'main' panicked at '"OGRField_struct_(unnamed_at_/Users/home/vcpkg/installed/arm64-osx/include/ogr_core_h_873_5)" is not a valid Ident', /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.49/src/fallback.rs:756:9
```

This error in particular happens with vcpkg, but same thing happens with brew version.

**Comment by lnicola** [comment]
That's strange, `cargo check --features bindgen` works for me with GDAL 3.6.3.

**Comment by milosimr** [comment]
Homebrew updated gdal to 3.6.3.1

**Comment by milosimr** [comment]
<img width="1663" alt="Screenshot 2023-04-13 at 13 51 28" src="https://user-images.githubusercontent.com/27823654/231750094-eded454d-b89d-4271-98c4-db313b8c7c06.png">

Sorry this is what I have on that line

**Comment by lnicola** [comment]
Yeah, I have those, too:

![image](https://user-images.githubusercontent.com/308347/231753646-f410cf4f-fe12-4b72-99b1-ff7450f93c74.png)

**Comment by lnicola** [comment]
This looks like https://github.com/rust-lang/rust-bindgen/issues/2312.

Are you building the current version of the code or the latest release? Which `bindgen` version do you have in your `Cargo.lock`?

**Comment by lnicola** [comment]
> I cloned gdal repo and ran cargo check --features bindgen and it works for me too.

Ah, so it's only in the released version?

**Comment by milosimr** [comment]
<img width="847" alt="Screenshot 2023-04-13 at 14 39 30" src="https://user-images.githubusercontent.com/27823654/231761039-8c60edee-e2fb-4025-a7de-1e4ff7a98f55.png">

This is what I have in my dependencies. I think I tried with git link to pull the latest code and had the same results, but can't say for sure.

**Comment by lnicola** [comment]
Try `cargo tree | grep bindgen`.

**Comment by milosimr** [comment]
Yeah, I tried that and it works, but a lot of things changed in the meantime so I get other compile errors.

**Comment by milosimr** [comment]
Thanks a lot for your help and responsiveness.

**Comment by lnicola** [comment]
When we put out a new release and you upgrade, you'll have to fix the same set of errors.

You can see the pending changes at https://github.com/georust/gdal/blob/master/CHANGES.md#unreleased. Feel free to ask here or on Discord if you need help upgrading! I'll try to find the time for another Lynch fan :-).

**Comment by alex-translation** [comment]
I had the same issue as @milosimr and this solution worked for me as well. Thank you @lnicola and I'm looking forward to future releases. Really enjoying the whole `georust` suite.
