### ISSUE TITLE
Release 0.15

### ISSUE THREAD

**Issue by metasim** [georust/gdal#399]
I'd like to advocate for a new release. It's been 6 months since 0.14. Internally in my org, we're building from GitHub URLs, which I don't like doing for too long.

I'd also like to learn how to do a release if the project owners are amenable to that.

## Open Items

https://github.com/georust/gdal/milestone/1

**Comment by metasim** [comment]
A convenience summary of the changes since 0.14:

---

- Added `SpatialRef::to_projjson`

  - <https://github.com/georust/gdal/pull/389>

- Added `Geometry::length`

  - <https://github.com/georust/gdal/pull/384>

- Added `Geometry::union`

  - <https://github.com/georust/gdal/pull/379>

- Added `Geometry::from_gml`

  - <https://github.com/georust/gdal/pull/378>

- Added `CoordTransform::new_with_options` and `CoordTransformOptions`

  - <https://github.com/georust/gdal/pull/372>

- Set the link flag of gdal-sys to "libgdal". Emit the libgdal version via cargo:version_number. Remove wrong build-dependency on gdal-sys and remove docs_rs workaround.

  - <https://github.com/georust/gdal/pull/377>

- Added `Geometry::from_geojson`

  - <https://github.com/georust/gdal/pull/375>

- Added `CslStringList::add_string`

  - <https://github.com/georust/gdal/pull/364>

- **Possibly breaking**: Set MSRV to 1.58.

  - <https://github.com/georust/gdal/pull/363>

- Added a `TryFrom` array implementation for `CslStringList`

  - <https://github.com/georust/gdal/pull/362>

- Added `Rasterband::c_rasterband` to obtain the raw C pointer to `GDALRasterBandH`

  - <https://github.com/georust/gdal/pull/359>

- **Breaking**: `Feature::geometry` returns an `Option<&Geometry>` instead of `&Geometry`. Calls to `Feature::geometry` will no longer panic.

  - <https://github.com/georust/gdal/pull/349>

- **Breaking**: `RasterBand::band_type` returns the `GdalDataType` enum instead of `GDALDataType::Type` ordinal. Fixes [#333](https://github.com/georust/gdal/issues/333)

  - <https://github.com/georust/gdal/pull/334>

- The default features of the `chrono` dependency are now disabled

  - <https://github.com/georust/gdal/pull/347>

- Added prebuilt bindings for GDAL 3.6 (released 6 November 2022).

  - <https://github.com/georust/gdal/pull/352>

- **Breaking**: `Layer::spatial_ref` returns `Option` instead of `Result`, thereby better reflecting the semantics documented in the [C++ API](https://gdal.org/doxygen/classOGRLayer.html#a75c06b4993f8eb76b569f37365cd19ab)

  - <https://github.com/georust/gdal/pull/355>

- Exposed various functions on `Geometry`: `make_valid`, `geometry_name`, and `point_count`.

  - <https://github.com/georust/gdal/pull/356>

- Exposed `read_arrow_stream` on `Layer` to access OGR's columnar reading API.

  - <https://github.com/georust/gdal/pull/367>

- Exposed spatial predicates over `Geometry`: `intersects`, `contains`, `disjoint`, `touches`, `crosses`, `within`, and `overlaps`.

  - <https://github.com/georust/gdal/pull/366>

- Added `Geometry::envelope` and `Geometry::envelope_3d`.

  - <https://github.com/georust/gdal/pull/370>

- Added support for getting the `SpatialRef` of embedded ground control points (GCPs) via `Dataset::gcp_spatial_ref`.

  - <https://github.com/georust/gdal/pull/397>

**Comment by lnicola** [comment]
I was planning to work on exposing the GCPs, since somewhat requested it recently, and it works as a counterpart to #397. What do you think?

**Comment by metasim** [comment]
> I was planning to work on exposing the GCPs

I started looking into that as well, and I came back to thinking we needed to define a better set of principles around pointers to foreign types, which led to the `foreign_types` prototype, which leads to a bunch of breaking changes, which leads to debates on if we should or shouldn't do it, etc. etc. etc 😆 

So it's one of those "is perfect being the enemy of good enough" evaluations. Where I sit right this moment is: Let's get what's working released now, and have a fresh baseline for the next round of improvements, which may or may not include cleaning up pointer handling.

What might help me in considering this is understanding the "cost of releasing". I've only been around for 2 or 3 releases, but each time it seems to create an urge to get straggling features in before cutting the release, making me believe that a release is a "costly" activity. 

Is this true, and if so, are there some structural changes we can make to enable us to more easily do releases more regularly? 

In my other projects I usually feel more comfortable when PRs can live unreleased state for a bit to allow willing participants to give them some extra testing before getting released, while unwilling users can just stick to feature that have matured for a while longer. But that's just personal preference.

**Comment by lnicola** [comment]
For GCP's, I think we could simply copy the data and return a `Vec`, bypassing the fancy pointer question. But okay, we can postpone that if you want. I'd still want to get in the GDAL 3.7 bindings though -- it shouldn't be hard, I can try that tomorrow.

> Is this true, and if so, are there some structural changes we can make to enable us to more easily do releases more regularly?

I'd personally like a workflow where we bump the version and it would get published automatically :sweat_smile:.

Other than that, no, I don't have any specific ideas.

**Comment by metasim** [comment]
> For GCP's, I think we could simply copy the data and return a Vec

I'm not adverse to that if it's just fetching the values. Would it be all of the fields [here](https://gdal.org/api/raster_c_api.html#_CPPv48GDAL_GCP)? 

Comprehensively speaking (again, beyond "good enough"?), I was assuming it would include: 
* `GDALInitGCPs` (`...::new`??)
* `GDALDeinitGCPs` (`Drop`??)
* `GDALDuplicateGCPs` (Clone??) 
* `GDALGCPsToGeoTransform`
* `GDALGetGCPCount`
* `GDALGetGCPProjection`
* `GDALSetGCPs`
* `GDALSetGCPs2`.

>  I'd still want to get in the GDAL 3.7 bindings though -- it shouldn't be hard, I can try that tomorrow.

Sounds great! Do it!

**Comment by metasim** [comment]
> I'd personally like a workflow where we bump the version and it would get published automatically.

I saw that in another project recently but forgot which. I'll see if I can find it. I think it was triggered from [`on.release` event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release), which is cool.

**Comment by jdroenner** [comment]
I am on vacation and will be back next week. Will look into this issue then :)

**Comment by lnicola** [comment]
> I saw that in another project recently but forgot which.

rowan does that by checking whether there's already a git tag with the current version. There's a little crate for it, xaction.

**Comment by metasim** [comment]
@lnicola Since we have a week until jdreonner gets back, would you like help on the GCP stuff? Want me to take an initial stab at it, or were you really wanting to do it?

**Comment by lnicola** [comment]
@metasim I pretty much got the GCP access working.

**Comment by jdroenner** [comment]
i'm back from vacation :)
Are there things we want to get into the release? Is the GCP access done?

**Comment by metasim** [comment]
@jdroenner I know this is annoying scope creep beyond the request to cut a release, but would you be willing to take a peek at #404 and #406 and give us your opinion of these API "shapes"? 

I think #404 is probably fine (I wonder if there's a way of removing the replication of C struct in Rust for instantiation convenience purposes). 

#406 has a situation where the C API uses the error code as side-band communications for indicating a default value was used, and the proposed solutions don't feel fully idiomatic.  

Whether or not we get these exact APIs "perfect" is probably not that critical, but I don't think they are unique, and your advice might help us come up with a replicable solution for future cases of similar shape.

**Comment by lnicola** [comment]
This is going to be the best release ever :smiley:.

**Comment by metasim** [comment]
Maybe we should blog/reddit about it (briefly) so we can announce it in This Week in Rust. 🤠 🦀 

See: [TWIR on link only announcements](https://twitter.com/U007D/status/1570265868000702466?s=20)

**Comment by metasim** [comment]
Anything else we want to add?

<img width="480" alt="image" src="https://github.com/georust/gdal/assets/131013/d3110429-244e-4a0e-9938-45885125ac28">

**Comment by lnicola** [comment]
I'm tempted to file a PR to tweak [this API](https://docs.rs/gdal/latest/gdal/raster/struct.RasterBand.html#method.actual_block_size), but I think we can stop now :-).

**Comment by metasim** [comment]
> I'm tempted to file a PR to tweak [this API](https://docs.rs/gdal/latest/gdal/raster/struct.RasterBand.html#method.actual_block_size), but I think we can stop now :-).

Interesting. I use this API at work. Are you looking to replace the tuples with something more semantically explicit?

**Comment by lnicola** [comment]
Yeah, to unpack the tuples. And I'm not use `isize` is useful there. I've used it a number of times, and it was always annoying :-). Anyway, doesn't matter.

**Comment by metasim** [comment]
> And I'm not use isize is useful there. 

IMO, the discrepancy between `isize`, `usize`, and `i32` is all over the place, and often the fault of the C API being unclear as to whether negative values are valid, niche or invalid. I'd suggest tackling that will take careful inspection of of the C code. It is annoying, but when i tried to normalize over it in my work code it became a mess.

**Comment by metasim** [comment]
@jdroenner Anything else we need to do or can help with to cut a release (and document the process)?

**Comment by lnicola** [comment]
I wouldn't be surprised if some format (looking at you, NetCDF) supports negative cell coordinates. :roll_eyes:

**Comment by lnicola** [comment]
Just asked on the mailing list, the block offsets are always positive.

**Comment by jdroenner** [comment]
i can do the release today if all PRs you want are merged. The process is not that complex. All i need to do is editing the changelog and running cargo release :sweat_smile:

**Comment by jdroenner** [comment]
https://crates.io/crates/gdal

**Comment by metasim** [comment]
Thanks @jdroenner !! 😄
