### ISSUE TITLE
Create CI builds against GDAL 3.6 & 3.7

### ISSUE THREAD

**Issue by metasim** [georust/gdal#403]
Should we consider dropping 3.2 and/or 3.3? Under what principles should we make that evaluation?

**Comment by jdroenner** [comment]
This is a really good question. My idea was to have a test for the GDAL included in the current Ubuntu LTS.  (and all GDAL versions released after that).

**Comment by lnicola** [comment]
Nominating this for the new release, since the 3.7 bindings are broken.

**Comment by metasim** [comment]
Fixed in #412

**Comment by jdroenner** [comment]
yes 22.04 is the latest LTS.
