### ISSUE TITLE
Warning 6: driver CSV does not support creation option SEPARATOR.(but ogr2ogr support)

### ISSUE THREAD

**Issue by wczyyqc** [georust/gdal#424]
i had tested following code in two machines, both them complains: ***Warning 6: driver CSV does not support creation option SEPARATOR.***
but if i run ```ogr2ogr test.csv test.geojson  -lco SEPARATOR=SEMICOLON  -lco GEOMETRY=AS_WKT``` from terminal, my computers can generate correct output csv file without any warning.

env of the first computer:
```
rustc 1.68.2 (9eb3afe9e 2023-03-27)
GDAL 3.2.2, released 2021/03/05
gdal = "0.15.0"
gdal-sys = "0.9.0"
```
and the sencond:
```
rustc 1.68.2 (9eb3afe9e 2023-03-27)
GDAL 3.5.1, released 2022/06/30
gdal = "0.14.0"
gdal-sys = "0.8.0"
```

my code: 
```rust
use std::path::Path;
use gdal::raster::RasterCreationOption;

fn main() {
    println!("{}",gdal::version::VersionInfo::version_summary()); 
    test_geojson("test.geojson");
}

fn test_geojson<T:AsRef<Path>>(src:T){

    let dst = gdal::Dataset::open(src).unwrap();
    let driver = gdal::DriverManager::get_driver_by_name("CSV").unwrap();
    let opt = RasterCreationOption{
        key: "SEPARATOR",
        value:"SEMICOLON"
    };
    let opt2 = RasterCreationOption{
        key: "GEOMETRY",
        value:"AS_WKT"
    };
    let name = "/vsimem/test.csv";
    // here opt2 worked but opt not
    let _ = dst.create_copy(&driver, name, &[opt,opt2]).unwrap();
    let csv = gdal::vsi::get_vsi_mem_file_bytes_owned(name).unwrap();
    let content = String::from_utf8(csv).unwrap();
    println!("{}",content);
}
``` 
could anyone help on this?

**Comment by jdroenner** [comment]
I guess "SEPARATOR" is an open option, not a creation option. Try to use `open_ex` and specify it as open option.

**Comment by wczyyqc** [comment]
> I guess "SEPARATOR" is an open option, not a creation option. Try to use `open_ex` and specify it as open option.

it is a create option according to [https://gdal.org/drivers/vector/csv.html#layer-creation-options](https://gdal.org/drivers/vector/csv.html#layer-creation-options),
and it did work in ogr2ogr when use as a -lco parameter (lco stands for layer create option, i guess).

i thought it might because create_copy did not support vectors creation(or csv creation) very well, but i`m not sure.

**Comment by rouault** [comment]
GDALCreateCopy() can only be used to pass dataset/datasource creation options, not layer creation options. For that, you'd instead need to use GDALVectorTranslate() which is the C callable version of ogr2ogr

**Comment by wczyyqc** [comment]
i got it, thank you for your reply.
