### ISSUE TITLE
Could not convert gdal version string into number with GDAL 3.7.2 Linux 64

### ISSUE THREAD

**Issue by latot** [georust/gdal#438]
Hi all, I'm trying to use the crate, sadly does not works.

```
gdal = {features = ["bindgen"], version = "0.16.0"}
gdal-sys = { version = "0.9.1", features = ["bindgen"] }
```

```
  --- stderr
  thread 'main' panicked at 'The GDAL-SYS crate must emit the version of libgdal via cargo:version_number: NotPresent', /home/pipe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gdal-0.16.0/build.rs:5:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

There is at least two issues here, one is related to the git version.

```
pkg-config --modversion gdal
3.7.2dev
```

Talking with @lnicola seems "3.7.2dev" can't be parsed.

The next and unknown one is that, using GDAL 3.7.2, not the dev version, the error persist... no idea why:

```
pkg-config --modversion gdal
3.7.2
```

I'm using gentoo 64.

Edited:

Running ```cargo clean``` after downgrade from gdal-git to 3.7.2 fixes the issue.
Probs this happens because of the ```3.7.2dev```

Thx!

**Comment by lnicola** [comment]
> Running cargo clean after downgrade from gdal-git to 3.7.2 fixes the issue.

For future reference, this is because build scripts don't run again unless something changed. Cargo can't tell when you've upgraded or downgraded GDAL, so you need to at least do `cargo clean -p gdal-sys` (but `cargo clean` is probably a better idea).
