### ISSUE TITLE
Define a policy for the supported GDAL versions

### ISSUE THREAD

**Issue by lnicola** [georust/gdal#477]
We currently test on 3.1 to 3.8 in the official images, and on 3.0 on Ubuntu 20.04 (LTS), while 2.4 [is broken](https://github.com/georust/gdal/issues/467). We should decide if we want to fix the latter or drop the support, and in the long run we probably don't want to test dozens of versions.

Popular distributions have:
 - Debian 12 (stable): 3.6.2
 - Debian 11 (oldstable): 3.2.2
 - Ubuntu 22.04: 3.4.1
 - Ubuntu 20.04: 3.0.4
 - Ubuntu 18.04 (EOL 2023): 2.2.3
 - EL 9: 3.4.3
 - EL 8 (EOL 2029): 3.0.4
 - EL 7 (EOL 2024): 1.11.4

(you can check others on https://pkgs.org/, search for `gdal` and `gdal-bin`)

I'm inclined to say we should use Ubuntu LTS-1 (20.04) or Debian oldstable, however:

 - we're missing a lot of functionality, and I can see people wanting to get that while still supporting older systems
 - I'm not a fan of singling out Ubuntu in our policy

CC @rouault maybe you have some idea of which versions people are using.

**Comment by lnicola** [comment]
> it really depends if your target audience is rather bleeding edge or conservative

Probably not very conservative if they're using Rust, but I don't really know. Any thoughts, @jdroenner, @metasim?

**Comment by jdroenner** [comment]
It is difficult... For me, Ubuntu is the most relevant (Linux) distribution. In my experience it is the one that is often used out of the box.
Maybe Ubuntu LTS (and/or Debian stable) is also ok if there is a long enough transition period when a new version is released.
