### ISSUE TITLE
`gdal` 0.17 tracker

### ISSUE THREAD

**Issue by lnicola** [georust/gdal#484]
We should probably put out another release, given the recently-added support for GDAL 3.8 and other improvements.

My wishlist, after skimming the open issues, but by no means definitive:

 - [ ] #483
 - [x] #495
 - [x] #477 - let's settle for Ubuntu LTS-1
 - [x] #432
 - [x] #427
 - [x] #494

Stretch goal:

 - [x] #485 
 - [x] #496

**Comment by metasim** [comment]
@lnicola I'd suggest us not including #483 in this release. We have lots of nice new features already, and that one feels like it needs some design/debate. Thoughts?

**Comment by metasim** [comment]
Maybe we should wrap up https://github.com/georust/gdal/pull/493 and add it to the release?

**Comment by lnicola** [comment]
Seems doable, but I don't really feel like messing around with VS (last time I tried to install the DDK and it was awful).
