### ISSUE TITLE
[Feature] Add `DriverIterator` to iterate through the available drivers

### ISSUE THREAD

**Issue by Atreyagaurav** [georust/gdal#512]
Following up from the discussions in #510.

I was thinking about it and came across a potential problem. We can add and remove the drivers during runtime, so if we keep track of the index and increase that to get the `Iterator::next()`, then we'll run into:
- Assuming count is same:
  + panic on `Driver::get(i)` if driver(s) is/are removed
  + miss the last driver(s) if driver(s) is/are added
- Assuming we check the count each time:
  + skip driver(s) if driver(s) is/are removed before current count
 
So, to make sure this doesn't happen, we can take a Vec of the Drivers and make an iterator out of it, but that defeats the purpose of the Iterators. But maybe that'll work, as we don't have to call the `get_driver(i)` ourselves in a loop.

**Comment by lnicola** [comment]
I think we can call `GDALGetDriver` until it returns `NULL`. If the user adds new drivers during iterator, they might even get them back.

There's no safety issue and we can add a note saying it's a bad idea to register or unregister drivers during the iteration.
