### ISSUE TITLE
Can it support macos?

### ISSUE THREAD

**Issue by bishen** [georust/gdal#515]
I successfully ran on Linux&Windows.
But we still need macos

**Comment by lnicola** [comment]
We don't test it at the moment. Is it not working, then? Any patches are welcome!

**Comment by JayKickliter** [comment]
I use this crate just fine on macOS.

**Comment by bishen** [comment]
% cargo run                           
   Compiling gdal-sys v0.9.1
error: failed to run custom build command for `gdal-sys v0.9.1`

Caused by:
  process didn't exit successfully: `/Users/bishen/www/test2/target/debug/build/gdal-sys-13c6e0836cf996f5/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=GDAL_STATIC
  cargo:rerun-if-env-changed=GDAL_DYNAMIC
  cargo:rerun-if-env-changed=GDAL_INCLUDE_DIR
  cargo:rerun-if-env-changed=GDAL_LIB_DIR
  cargo:rerun-if-env-changed=GDAL_HOME
  cargo:rerun-if-env-changed=GDAL_VERSION
  cargo:rustc-link-lib=dylib=gdal
  cargo:rustc-link-search=/opt/homebrew/lib
  cargo:rerun-if-env-changed=GDAL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:version_number=3080300
  cargo:rustc-cfg=gdal_sys_3_8_3

  --- stderr
  thread 'main' panicked at /Users/bishen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gdal-sys-0.9.1/build.rs:240:17:
  No pre-built bindings available for GDAL version 3.8. Use `--features bindgen` to generate your own bindings.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by bishen** [comment]
> 我在 macOS 上使用这个板条箱很好，带有 和`brew install goal``gdal = { version = "0.16", features = ["bindgen"] }`

I have already installed it  `brew install goal`  `gdalinfo --version   3.8.3`

**Comment by bishen** [comment]
> I use this crate just fine on macOS with `brew install goal` and `gdal = { version = "0.16", features = ["bindgen"] }`

I have already installed it brew install `brew install goal `gdalinfo --version   3.8.3`

**Comment by JayKickliter** [comment]
> I have already installed it brew install `brew install goal `gdalinfo --version 3.8.3`

Sorry, I typed the wrong package name. Just be very clear, it's `brew install gdal`.

**Comment by lnicola** [comment]
>  No pre-built bindings available for GDAL version 3.8. Use --features bindgen to generate your own bindings.

You'll have to do just that, downgrade to an older GDAL, or use a `-git` dependency (the next release is coming out soon-ish).
