### ISSUE TITLE
No pre-built bindings available for GDAL version 3.8

### ISSUE THREAD

**Issue by Barugon** [georust/gdal#535]
After updating to Rust 1.78, I get the error `No pre-built bindings available for GDAL version 3.8`. A look into the `prebuilt-bindings` folder confirms that `gdal_3.8.rs` is missing.

**Comment by lnicola** [comment]
The bindings exist, but not in the released version. You need to use a `git` or `--features bindgen`. This has nothing to do with the Rust version.
