### ISSUE TITLE
Suppress print messages from underlying lib

### ISSUE THREAD

**Issue by TennisBowling** [georust/gdal#544]
Hey all, GDAL prints when there's an error
with this code:
```rust
fn get_elev(band: &RasterBand, transform: &[f64; 6], lat: &f64, lon: &f64) -> f64 {
    let col = ((lon - transform[0]) / transform[1]) as isize;
    let row = ((lat - transform[3]) / transform[5]) as isize;

    let buf = match band.read_as::<f64>(
        (col, row),
        (1, 1),
        (1, 1),
        Some(gdal::raster::ResampleAlg::CubicSpline),
    ) {
        Ok(buf) => buf,
        Err(_) => {
            return f32::MIN as f64;
        }
    };
    buf.data()[0]
}
```

the err handle of the match works well, but it seems the underlying gdal lib prints this
```
ERROR 5: ./elev.tif, band 1: Access window out of range in RasterIO().  Requested
(86761,28098) of size 1x1 on raster of 86412x54012.
```

Is there any way to turn off these messages apart from redirecting stderr? it seems the python version has something: https://gis.stackexchange.com/questions/73463/gdal-and-python-dont-print-gdal-error-messages

**Comment by ChristianBeilschmidt** [comment]
Could you try https://docs.rs/gdal/0.17.1/gdal/config/fn.set_error_handler.html?

**Comment by TennisBowling** [comment]
Spot on. Thanks!
