### ISSUE TITLE
release 0.18.0 or 0.17.1

### ISSUE THREAD

**Issue by jdroenner** [georust/gdal#557]
Release an new version including fixes for the buffer type

Since we still have a 0.*.* Version I guess we can ship 0.18.0.
@lnicola what do you think? Also are there other things we should include? 

(I can do the release tomorrow morning. Not at home today, sorry)

**Comment by lnicola** [comment]
I think we should release 0.17.1 now, and 0.18.0 with more changes (the bundling PR, at least).

**Comment by jdroenner** [comment]
v 0.17.1 is now at crates.io thanks to all involved in this release. Lets plan the next feature release :)
