### ISSUE TITLE
.pbf supporting

### ISSUE THREAD

**Issue by usagi** [georust/gdal#64]
Hi, is it not supported .pbf (.osm.pbf) yet? How can I open and use .pbf if supported.

-----
.pbf examples is here: https://download.geofabrik.de/

**Comment by pka** [comment]
pbf are supported, if GDAL is built with pbf support. You can open it like any other vector source.

**Comment by vinayakkulkarni** [comment]
An example would be great @pka

**Comment by lnicola** [comment]
@vinayakkulkarni see https://github.com/georust/gdal/blob/master/examples/read_write_ogr.rs, if you haven't.
