### ISSUE TITLE
Dataset should be Send

### ISSUE THREAD

**Issue by rmanoka** [georust/gdal#70]
To the best of our understanding, GDAL supports minimal multi-threading in that it is okay for different threads to access a Dataset as long as only one thread is accessing it at any time (see [GDAL Doc](https://gdal.org/api/raster_c_api.html#_CPPv48GDALOpenPKc10GDALAccess)).

I believe we should implement `Send` trait on `{raster,vector}::Dataset` to allow it to be passed across threads if necessary.   As `Dataset` is not `Clone` or `Copy`, there is still only one copy of the handle.   Note that `RasterBand` and `Layer` should not be `Send` because they allow reference back to `Dataset` and may cause concurrent calls to the GDAL layer.

We have encountered this use-case when creating multi-threaded pipeline to work on large (> 4GB) datasets.  Also happy to provide a PR.

**Comment by jdroenner** [comment]
will fix this in https://github.com/georust/gdal/pull/99

**Comment by ChristianBeilschmidt** [comment]
I agree with you, it should be `Send` but not `Sync`. The structs are not `Send` by default because they use pointers, but they are encapsulated to not hurt the constraints I guess.

Maybe it is better to not keep the backreference for `RasterBand` and `Layer` to the `Dataset`.

**Comment by jdroenner** [comment]
@ChristianBeilschmidt  #98 will remove the references following this approach: https://medium.com/dwelo-r-d/wrapping-unsafe-c-libraries-in-rust-d75aeb283c65

**Comment by rmanoka** [comment]
@jdroenner We experimented with `Send` in a fork of this repo, and it works fine for most formats.  However, I'm specifically worried about VRT datasets.  This [link](https://gdal.org/drivers/raster/vrt.html#multi-threading-issues) mentions that GDAL >= 2.3 does the "right thing" with VRT datasets, but before that it was not safe to even send the handle to another thread!   May be we should add the `Send` only if we are compiling against libgdal 2.3 or greater?

Just for reference, it looks like opening with `Shared` flag from different threads is not an issue since GDAL 1.6.0 (see [here](https://gdal.org/doxygen/gdal_8h.html#a347b1025e090c5238196b658463addd3)), so we are good to go there.

**Comment by jdroenner** [comment]
This is a good find. We should really only allow this from 2.4 on. I think versions under GDAL 2.4 are very rare and therefore this should not be a problem for anyone.
