### ISSUE TITLE
Adapt to GDAL 3

### ISSUE THREAD

**Issue by jdroenner** [georust/gdal#74]
GDAL 3 introduces large changes. We should decide how to handle them in this crate.

Some (but not all) options are:

1. The easiest way would be to drop support for GDAL < 3.0.
2. Use modules and features as feature gate. This would result in separate modules with methods from gdal 2.4, gdal 3.0, ...

**Comment by pka** [comment]
@jdroenner I would be interested in this discussion. I'm currently on the Discord channel and also available for a voice discussion in german.

**Comment by pka** [comment]
As discussed I'm fine both with starting a GDAL 2 maintenance branch and concentrate on GDAL 3 and with using feature gates. I think with a few additional methods for GDAL 2 (see review of #75), both versions could be maintained in one branch, which I would prefer, if feasable.

**Comment by jdroenner** [comment]
master is now based on GDAL 2.0 (#96)
