### ISSUE TITLE
Replace "failure" error handling

### ISSUE THREAD

**Issue by jdroenner** [georust/gdal#76]
Handling gdal crate errors in other crates requires the "failure" crate which is deprecated. We should use a crate / error strategy which does not require additional crates.

**Comment by pka** [comment]
My preference would be https://github.com/dtolnay/thiserror, which is used in https://github.com/georust/proj as well. I could also help you with this task

**Comment by urschrei** [comment]
Just to add that my experience using thiserror in `proj` has been very positive. The only drawback is its dependency on `syn`, which adds to compile times, but it's worth it in my opinion.
